[package]
name = "heuristic"
version = "0.1.0"
authors = ["Sam Blazes <sblazes@caltech.edu>"]

[dependencies]
bitboard = {path = "../bitboard"}
pattern_engine = {path = "../pattern_engine"}
rand = "0.3"
serde = "1.0.8"
serde_derive = "1.0.8"
serde_json = "1.0.2"